version: "3.8"

services:
  postgresql:
    restart: always
    image: 'postgres:latest'
    container_name: post_offices_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mcpmwC8gGwVKr4Q9xCKZEzEgS
      - POSTGRES_DB=pejt_office
    ports:
      - "5435:5432"

#   zookeeper:
#     image: confluentinc/cp-zookeeper:latest
#     container_name: zookeeper
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#   broker:
#     image: confluentinc/cp-kafka:latest
#     container_name: broker
#     ports:
#       - 9092:9092
#     depends_on:
#       - zookeeper
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  postofficeapp:
#    image: 'application:latest'
#    build:
#      context: .
#    container_name: postofficeapp
#    ports:
#      - 10100:10100