spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/pejt_office
    username: postgres
    password: mcpmwC8gGwVKr4Q9xCKZEzEgS
    hikari:
      maximum-pool-size: 3
  jpa:
    show-sql: true
server:
  port: 8084
interceptor:
  kafka:
    bootstrap: "localhost:9092"
    topic: "url"